name: firestore_repository
description: Pacote para abstrair funções do Firestore
publish_to: none

version: 1.0.0

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  firebase_core: ^1.10.6
  cloud_firestore: ^3.1.5


dev_dependencies:
  flutter_lints: ^1.0.0