name: authentication_repository
description: Pacote para abstrair funções da Autenticação
publish_to: none

version: 1.0.0

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:

dev_dependencies:
  flutter_lints: ^1.0.0