name: products_repository
description: Pacote para abstrair funções dos Produtos
publish_to: none

version: 1.0.0

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.5
  firestore_repository:
    path: ../firestore_repository


dev_dependencies:
  flutter_lints: ^1.0.0