name: realtime_database_repository
description: Pacote para abstrair funções do Realtime Database
publish_to: none

version: 1.0.0

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  firebase_core: ^1.10.6
  firebase_database: ^9.0.4


dev_dependencies:
  flutter_lints: ^1.0.0