name: pdf_repository
description: Pacote para abstrair funções da criação de PDFs
publish_to: none

version: 1.0.0

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  pdf: ^3.6.5
  path_provider: ^2.0.8
dev_dependencies:
  flutter_lints: ^1.0.0